// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkRgTY4hL8MoTTksV9g8Opf6lys4LIrrM',
    appId: '1:1023154577652:web:66659d9f0195b7143b3ea1',
    messagingSenderId: '1023154577652',
    projectId: 'examenflutterfirebase-vasquezs',
    authDomain: 'examenflutterfirebase-vasquezs.firebaseapp.com',
    storageBucket: 'examenflutterfirebase-vasquezs.firebasestorage.app',
    measurementId: 'G-WW0P2TW238',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQ6ZUcc-mrjHrARi_dqMHEUrfkw1iiHo',
    appId: '1:1023154577652:android:958d21b92da3dc603b3ea1',
    messagingSenderId: '1023154577652',
    projectId: 'examenflutterfirebase-vasquezs',
    storageBucket: 'examenflutterfirebase-vasquezs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgCiWtwNl9RcPDw3YdGYQqrI6Im5qq3M',
    appId: '1:1023154577652:ios:9b2a4a13ab923c8a3b3ea1',
    messagingSenderId: '1023154577652',
    projectId: 'examenflutterfirebase-vasquezs',
    storageBucket: 'examenflutterfirebase-vasquezs.firebasestorage.app',
    iosBundleId: 'com.example.vasquezsaldanafrancoaron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgCiWtwNl9RcPDw3YdGYQqrI6Im5qq3M',
    appId: '1:1023154577652:ios:9b2a4a13ab923c8a3b3ea1',
    messagingSenderId: '1023154577652',
    projectId: 'examenflutterfirebase-vasquezs',
    storageBucket: 'examenflutterfirebase-vasquezs.firebasestorage.app',
    iosBundleId: 'com.example.vasquezsaldanafrancoaron',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkRgTY4hL8MoTTksV9g8Opf6lys4LIrrM',
    appId: '1:1023154577652:web:afc90e77a3dbb0a53b3ea1',
    messagingSenderId: '1023154577652',
    projectId: 'examenflutterfirebase-vasquezs',
    authDomain: 'examenflutterfirebase-vasquezs.firebaseapp.com',
    storageBucket: 'examenflutterfirebase-vasquezs.firebasestorage.app',
    measurementId: 'G-FWVJE9T2BB',
  );
}
